URL_BASE = "https://api.pushwoosh.com"
URL_EXPORT_SEGMENT = URL_BASE + "/api/v2/audience/exportSegment"
URL_EXPORT_SEGMENT_RESULT = URL_BASE + "/api/v2/audience/exportSegment/result"
URL_REGISTER_DEVICE = URL_BASE + "/json/1.3/registerDevice"
URL_SET_TAGS = URL_BASE + "/json/1.3/setTags"
URL_UNREGISTER_DEVICE = URL_BASE + "/json/1.3/unregisterDevice"
URL_DELETE_DEVICE = URL_BASE + "/json/1.3/deleteDevice"
